# Generated by Django 4.0.6 on 2022-11-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_rename_email_review_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Img', models.ImageField(upload_to='')),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('Description', models.CharField(max_length=250)),
                ('Notes', models.CharField(max_length=150)),
            ],
        ),
    ]
