# Generated by Django 4.0.6 on 2022-11-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Img',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Item_Name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Price',
        ),
        migrations.AddField(
            model_name='order',
            name='Notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='Item',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='Notes',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
