# Generated by Django 4.0.6 on 2022-11-10 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_alter_service_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10)])),
                ('Delivery_Date', models.DateField(help_text='YYYY-MM-DD format')),
                ('Notes', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='First_Name',
            new_name='Item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Delivery_Date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Phone',
        ),
        migrations.AddField(
            model_name='order',
            name='Quantity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Notes',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')]),
        ),
    ]
