# Generated by Django 4.0.6 on 2022-11-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_rename_id_order_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Price',
            field=models.IntegerField(default=20.22),
            preserve_default=False,
        ),
    ]
