# Generated by Django 4.0.6 on 2022-11-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
