# Generated by Django 4.0.6 on 2023-01-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0003_alter_weightconvert_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Length', models.IntegerField()),
                ('Special', models.BooleanField()),
            ],
        ),
    ]
