# Generated by Django 4.0.6 on 2023-01-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0006_passwordgen_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=250)),
                ('Message', models.CharField(max_length=250)),
                ('From', models.EmailField(max_length=254)),
                ('To', models.EmailField(max_length=254)),
            ],
        ),
    ]
