# Generated by Django 4.0.6 on 2022-12-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('unit', models.IntegerField(choices=[(1, 'kilograms'), (2, 'pounds')])),
            ],
        ),
    ]
