# Generated by Django 4.0.6 on 2022-12-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightconvert',
            old_name='weight',
            new_name='Weight',
        ),
        migrations.RemoveField(
            model_name='weightconvert',
            name='unit',
        ),
        migrations.AddField(
            model_name='weightconvert',
            name='Unit',
            field=models.IntegerField(choices=[('kilograms', 'Kilograms'), ('pounds', 'Pounds')], default=12),
            preserve_default=False,
        ),
    ]
