# Generated by Django 4.0.6 on 2022-12-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0002_rename_weight_weightconvert_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightconvert',
            name='Unit',
            field=models.CharField(choices=[('KG', 'KG'), ('LB', 'LB')], max_length=100),
        ),
    ]
