# Generated by Django 4.0.6 on 2023-01-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0005_remove_passwordgen_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordgen',
            name='Special',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
