# Generated by Django 4.0.6 on 2023-01-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feet', models.IntegerField()),
                ('Inches', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('Unit', models.CharField(choices=[('KG', 'KG'), ('LB', 'LB')], max_length=100)),
            ],
        ),
    ]
