# Generated by Django 4.0.6 on 2022-11-09 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_review_remove_order_notes_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1, error_messages={'max_value': 'max value is 5', 'min_vlaue': 'min value is 1'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
