# Generated by Django 4.0.6 on 2022-11-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_alter_order_first_name_alter_order_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='Delivery_Date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='Phone',
        ),
    ]
