# Generated by Django 4.0.6 on 2022-11-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_alter_order_delivery_date_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='last_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.AlterField(
            model_name='order',
            name='Delivery_Date',
            field=models.DateField(help_text='YYYY-MM-DD format'),
        ),
        migrations.AlterField(
            model_name='order',
            name='First_Name',
            field=models.CharField(max_length=100),
        ),
    ]
