# Generated by Django 4.0.6 on 2022-11-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='Id_Number',
        ),
    ]
