# Generated by Django 4.0.6 on 2022-11-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
            preserve_default=False,
        ),
    ]
